### ISSUE TITLE
cached NativeLstm2 freezes with numpy 1.15.2

### ISSUE THREAD

**Issue by patrick-wilken** [rwth-i6/returnn#68]
I have the issue, that RETURNN freezes on running the TF session (TFEngine.py line 597) when loading compiled ops for the NativeLstm2 from cache. CPU usage is at 100%, but graph computation does not terminate.

Steps to reproduce:

```
python3 -m venv venv_nativeLstmDebug
source venv_nativeLstmDebug/bin/activate
cd /path/to/returnn && pip3 install -r requirements.txt  # installs numpy 1.15.2
# install tensorflow (tested with both version 1.11 from source and 1.4.1 via pip)

rnn.py demos/demo-tf-native-lstm2.12ax.config 
# runs as expected, output includes "OpCodeCompiler call: g++ [...]"
# ctrl-c

rnn.py demos/demo-tf-native-lstm2.12ax.config
# freezes, no such output (uses cached ops)
```

`rm -rf /tmp/$USER/returnn_tf_cache/ops/ ` solves the issue for the next run.
`pip3 install numpy==1.14.5` solves the issue permanently.
The same issue exists with NativeLstm, but not with the remaining LSTM types.

**Edit**: Problem seems to exist for all versions > 1.14.5, which is fishy, as we have 1.14.5 installed system wide (outside of venv).

**Comment by albertz** [comment]
This might be related to how we link the sgemm functions for the CPU variant of native LSTM. This is anyway very hacky and should be fixed. Maybe we should just wrap the Eigen matrix multiplication, which is also the fallback in the official TF `MatMul`/`BatchMatMul` op.

**Comment by albertz** [comment]
Btw, maybe also related, or maybe not: It seems a lot of tests are currently not working correctly on Travis. This seems to be since TensorFlow 1.11, but maybe also with a newer Numpy now (I didn't check that).

**Comment by albertz** [comment]
I pushed a few changes which might have impacted this.
My goal was to fix the Travis errors, but I was still not successful. E.g. check [here for a recent log](https://travis-ci.org/rwth-i6/returnn/jobs/438650851).
However, maybe also recheck your case.

**Comment by patrick-wilken** [comment]
With the current version of the code the issue still exists for the nativelstm2 demo mentioned above. However, in my real use case (encoder-decoder architecture using SprintDataset) the problem seems to have disappeared.

I noticed that in the case where it works, in the `info.py` the two arguments marked with "# only in demo" are missing, maybe that helps for debugging:

```
{
'base_name': 'NativeLstm2',
'c_macro_defines': {},
'code_hash': '4b5257c4978cc505a9e14c90857d80c3',
'code_version': (),
'include_paths': [
'/home/pwilken/venv_upstream_tf/lib/python3.5/site-packages/tensorflow/include',
'/home/pwilken/venv_upstream_tf/lib/python3.5/site-packages/tensorflow/include/external/nsync/public',
],
'ld_flags': [
'-lblas',  # only in demo
'-lf77blas',  # only in demo
'-L/home/pwilken/venv_upstream_tf/lib/python3.5/site-packages/numpy/.libs',
'-lopenblasp-r0-8dca6697.3.0.dev',
'-L/home/pwilken/venv_upstream_tf/lib/python3.5/site-packages/tensorflow',
'-ltensorflow_framework',
],
'nvcc_opts': (),
'tf_version': '1.11.0-rc1',
'with_cuda': False,
}
```

**Comment by albertz** [comment]
Try again with the latest Returnn version. Those ld flags should now appear at the end (if they appear at all; I think they should not appear at all anymore). And that should probably not make a difference then.

**Comment by patrick-wilken** [comment]
Nope, I still get exactly the same file for the demo.

For the other system it changed to:

```
{
'base_name': 'NativeLstm2',
'c_macro_defines': {},
'code_hash': 'bd0b82950a35e27b1ae3c962e41f640a',
'code_version': (),
'include_paths': [
'/home/pwilken/venv_upstream_tf/lib/python3.5/site-packages/tensorflow/include',
'/home/pwilken/venv_upstream_tf/lib/python3.5/site-packages/tensorflow/include/external/nsync/public',
],
'ld_flags': [
'-L/home/pwilken/venv_upstream_tf/lib/python3.5/site-packages/scipy/.libs',
'-l:libopenblasp-r0-39a31c03.2.18.so',
'-L/home/pwilken/venv_upstream_tf/lib/python3.5/site-packages/numpy/.libs',
'-l:libopenblasp-r0-8dca6697.3.0.dev.so',
'-L/home/pwilken/venv_upstream_tf/lib/python3.5/site-packages/tensorflow',
'-ltensorflow_framework',
],
'nvcc_opts': (),
'tf_version': '1.11.0-rc1',
'with_cuda': False,
}
```

**Comment by albertz** [comment]
So, how does it look in the demo exactly? Can you also post that?

**Comment by patrick-wilken** [comment]
Sorry for the delay. As I said, for the demo it's exactly the same as before:

```
{
'base_name': 'NativeLstm2',
'c_macro_defines': {},
'code_hash': '4b5257c4978cc505a9e14c90857d80c3',
'code_version': (),
'include_paths': [
'/home/pwilken/venv_upstream_tf/lib/python3.5/site-packages/tensorflow/include',
'/home/pwilken/venv_upstream_tf/lib/python3.5/site-packages/tensorflow/include/external/nsync/public',
],
'ld_flags': [
'-lblas',
'-lf77blas',
'-L/home/pwilken/venv_upstream_tf/lib/python3.5/site-packages/numpy/.libs',
'-lopenblasp-r0-8dca6697.3.0.dev',
'-L/home/pwilken/venv_upstream_tf/lib/python3.5/site-packages/tensorflow',
'-ltensorflow_framework',
],
'nvcc_opts': (),
'tf_version': '1.11.0-rc1',
'with_cuda': False,
}
```

By the way, where you able to reproduce this?

**Comment by albertz** [comment]
I'm not able to reproduce your hang or any nan (on any of my machines). I just see the error on Travis.

But I'm really wondering about your info dict from the demo. This cannot be the newest Returnn version. With the newest Returnn version, the ld_flags will definitely look different. See code. E.g. you will not have `-lopenblas...` but instead `-l:libopenblad...`. And the `-lblas` and `-lf77blas`  will come last, not first. Add a `print` to the code, or a breakpoint, to check that.

**Comment by patrick-wilken** [comment]
Ouch, you are right! I had a link to another rnn.py in my bin folder... With the current code I don't observe any freezes anymore.
For the real experiment I always used the full path, i.e. the right code version. I checked that for the demo the issue was actually resolved at the same time (commit 1481a3a).

For completeness, the info.py file is now:
```
{
'base_name': 'NativeLstm2',
'c_macro_defines': {},
'code_hash': '4b5257c4978cc505a9e14c90857d80c3',
'code_version': (),
'include_paths': [
'/home/pwilken/venv_upstream_tf/lib/python3.5/site-packages/tensorflow/include',
'/home/pwilken/venv_upstream_tf/lib/python3.5/site-packages/tensorflow/include/external/nsync/public',
],
'ld_flags': [
'-L/home/pwilken/venv_upstream_tf/lib/python3.5/site-packages/numpy/.libs',
'-l:libopenblasp-r0-8dca6697.3.0.dev.so',
'-L/home/pwilken/venv_upstream_tf/lib/python3.5/site-packages/scipy/.libs',
'-l:libopenblasp-r0-39a31c03.2.18.so',
'-L/home/pwilken/venv_upstream_tf/lib/python3.5/site-packages/tensorflow',
'-ltensorflow_framework',
],
'nvcc_opts': (),
'tf_version': '1.11.0-rc1',
'with_cuda': False,
}
```

**Comment by albertz** [comment]
Ok, good. :) Then I guess we can close this.
